Align with the scope of WSON topology
ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang pull request #1
Opened 2020-09-18 07:23 UTC by italobusi

Aligned with the scope of wson-topology and with the latest version of layer0-types

Co-authored-by: danielkinguk

2020-09-18 14:18 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
Two comments here:
1) this is related to l0-types:l0-label-range-info: the  definition in l0-types is very confusing. The term label is misleading, I know the need for alignment with teas-topology, but a more clear description of which information is provided in the grouping is needed . 
2) Why you need to augment LTP source netry of connectiivty matrix with grid information? I possible to add  a brief description of the technical scope : since the term (label) is already misleading at least a clear description is needed.

2020-09-18 14:55 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
Need a clear description of the scope of the augmentation with l0-label-range-info.

2020-09-18 14:55 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
same as previous comment

2020-09-18 14:56 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
same comment

2020-09-18 15:00 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
Also for Local Link Connectivity List entries, it is needed an explanation of the scope of the augmentation with l0-labe-range-info. This comment is valid also of the previous augmentation of TTP.

2020-09-18 15:04 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
Again , due to the misleading name , it is not clear the intention of this specific augmentation: label-range is in fact just information regarding the grid type

2020-09-18 15:58 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
Also for te-link it is needed to have a description of the scope of this augmentation

2020-09-18 16:07 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-start-end;
l0-types:flexi-grid-label-start-end is practically the n value to claculate nominal central frequency.  Is possible to have a description of the meaning of this augmentation?

2020-09-18 16:07 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-start-end;
same as previous comment.

2020-09-18 16:14 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-hop;
Again two problems:
1)  Augmentation description 
2) In l0-types  flexi-grid-label-hop description is not clear : what does it mean flexi grid path label ??

2020-09-18 16:22 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-start-end;
Augmentation description and misleading term for flexi-grid-label-start-end: it is expecting two labels but instead is just one

2020-09-18 16:27 UTC, sergiobelotti requested changes
In general, the changes are all augmentation without explicit description of the scope of that augmentation: why to add that specific parameter/entity?
Second, but it is not a problem of flex-grid, the module is using l0-types definitons , not clear and that need to be completed with better description. I put comment along the file.

2020-09-21 01:50 UTC, haomianzheng commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
A follow up question here: 
Shall we use the grouping 'l0-label-range-info'? or 'flexi-grid-label-range-info'? both of them are defined in ietf-layer0-types, and I am preferring the latter... 

Checking the details of the two groupings: 
l0-label-range-info: provide grid-type (expected to be flexi-grid-dwdm here) and the priority in RFC4203; 
flexi-grid-label-range-info: include all l0-label-range-info, and also include SWG and min/max slot width factor, this grouping is specially designed for this module. 

Moreover, if we don't use flexi-grid-label-range-info in this module (as the current shape), we should remove it from layer0-types.

2020-09-21 01:51 UTC, haomianzheng commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
same above.

2020-09-21 02:07 UTC, haomianzheng commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-hop;
Not a question to this model but to flexi-grid scope: are we supporting super channel? We are not doing this in GMPLS flexi-grid, so that we suggest to remove it. 

Then we may need to change the layer0-types, and keep flexi-grid-label-hop to contain only single channel. (Let's report in the interim and then check whether we change l0-types or not. )

2020-09-21 02:14 UTC, haomianzheng requested changes
Comments provided with changes requesting...

2020-09-21 02:17 UTC, haomianzheng commented
> In general, the changes are all augmentation without explicit description of the scope of that augmentation: why to add that specific parameter/entity?
> Second, but it is not a problem of flex-grid, the module is using l0-types definitons , not clear and that need to be completed with better description. I put comment along the file.

A question for clarification on the first point, are we looking for 'why to add' or 'what to be added'? I am preferring the latter as it makes sense to explain how the augmentation is done and what can be achieved by providing guidances. To answer 'why' it's a problem more to generic TE models, not tech-specific models. 

I agree that we should give more explicit descriptions. The proper place is in this model, not in ietf-layer0-types. Once we confirm which grouping should be used, we need to indicate those leaf/list/container usage in the description section of this model.

2020-09-21 14:42 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
Regarding Sergio's comment (https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/pull/1/files?file-filters%5B%5D=.yang#r490981902), it seems worthwhile describing the concept of layer0 labels in layer0-types-ext draft:

https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/issues/5

Regarding Haomain's comment (https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/pull/1/files?file-filters%5B%5D=.yang#r491763723), the l0-types:flexi-grid-label-range-info grouping should be used:

2020-09-21 14:43 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
See comment above

2020-09-21 14:44 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
See comment above

2020-09-21 14:45 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
See comment above

2020-09-21 14:45 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
See comment above

2020-09-21 14:47 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-start-end;
See comment above

2020-09-21 14:49 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-start-end;
See comment above

2020-09-21 14:49 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-hop;
Fixed description in layer0-types:

2020-09-21 14:49 UTC, italobusi commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-start-end;
Fixed description in layer0-types:

2020-09-21 14:57 UTC, haomianzheng commented on ietf-flexi-grid-topology.yang
> +      uses l0-types:flexi-grid-label-hop;
> Not a question to this model but to flexi-grid scope: are we supporting super channel? We are not doing this in GMPLS flexi-grid, so that we suggest to remove it.
> 
> Then we may need to change the layer0-types, and keep flexi-grid-label-hop to contain only single channel. (Let's report in the interim and then check whether we change l0-types or not. )

agreed to withdraw the comment, i.e., include the super channel case in the module.

2020-09-21 15:45 UTC, agva123 commented
Requested changes were discussed and addressed by Italo's commits.

2020-09-21 15:54 UTC, merged

2020-09-28 09:38 UTC, sergiobelotti commented on ietf-flexi-grid-topology.yang
> +    uses l0-types:l0-label-range-info;
@italobusi : Agree, and commented in https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/issues/5#issuecomment-699895542